### ISSUE TITLE
update TD logo in footer

### ISSUE THREAD

**Issue by attentioneering** [hypenotic/park-grants-fr#2]
Please update the footer component on the FR TD Grants page (https://parkpeople.ca/boursesdeparc/) to use the following lockup:

FR:
![TDReadyCommitment_LockupFR](https://user-images.githubusercontent.com/46387723/73382439-82308680-4295-11ea-83a2-c72b3d374e6a.png)

Some minor padding changes may be required.
Here's what the old one looks like:
<img width="1096" alt="Screen Shot 2020-01-29 at 12 47 47" src="https://user-images.githubusercontent.com/46387723/73382474-95dbed00-4295-11ea-908b-0b2b43047736.png">

**Comment by hubret** [comment]
93267c8
